name: ai_cruise
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
flutter:
  uses-material-design: true
